### ISSUE TITLE
Errors when testing DCNS

### ISSUE THREAD

**Issue by sharlec** [Cloudslab/iFogSim#10]
Hi,
I am trying to make the ifogsim and ifogsim2 running. They both have the same error messages as:

Starting DCNS...
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The constructor AppModule(int, String, String, int, double, int, long, long, String, CloudletScheduler, Map<Pair<String,String>,SelectivityModel>) refers to the missing type Pair
	Pair cannot be resolved to a type

	at ifogsim_1/org.fog.application.Application.addAppModule(Application.java:65)
	at ifogsim_1/org.fog.test.perfeval.DCNSFog.createApplication(DCNSFog.java:233)
	at ifogsim_1/org.fog.test.perfeval.DCNSFog.main(DCNSFog.java:68)

I am using JDK13.0.2.

**Comment by Samodhap** [comment]
Hi,
AppModule class uses the Pair implementation available in "org.apache.commons.math3.util.Pair". So please make sure to add all the the external libraries in the "JARs" Folder (https://github.com/Cloudslab/iFogSim/tree/main/jars)  to your project when running.
Hope this helps.

**Comment by sharlec** [comment]
Hi,

Thanks for mentioning the libraries. I just double checked my external libraries and I realized that I forget to unzip the common_math.jar.

However, after unzip the jars and have the same library setting as tutorial https://www.youtube.com/watch?v=uqg7TcOQS5Q,

I get a new error showing as:
The archive: /ifogsim_1/jars/commons-math3-3.5-javadoc.jar which is referenced by the classpath, does not exist.

What is the commons-math3-3.5-javadoc.jar? it is not in the tutorial but in a folder.

**Comment by sharlec** [comment]
I also noticed that some test cases work, but some do not.

In the test.perfeval folder, if I run DCNSFog.java or TranslationService then the previous errors show up; if i run microserviceAppSample2.java, TwoApps.java or VRGameFog.java then they work as expected.

**Comment by Samodhap** [comment]
Hi, 
i guess your class path refers to a different jar. 
https://github.com/Cloudslab/iFogSim/tree/main/jars/commons-math3-3.5 
The jar inside this folder is  the one it should be referring to.

**Comment by sharlec** [comment]
thanks for quick response. I just double check my files and I am sure the class path refer to the file in the mentioned folder.

**Comment by Samodhap** [comment]
Hi, To assist further with this, would it be possible to post screenshots of your class path libraries either from run configurations or the project structure ?

**Comment by sharlec** [comment]
![image](https://user-images.githubusercontent.com/25064369/166620011-e35003d1-1319-40e4-b1fb-91ea6b13fb0a.png)

**Comment by sharlec** [comment]
![image](https://user-images.githubusercontent.com/25064369/166620104-0022f72c-7ec3-46ca-a416-1a42ed26fcf7.png)

**Comment by Samodhap** [comment]
Please try removing commons-math3-3.5-javadoc.jar in your classpath and running again
![166620104-0022f72c-7ec3-46ca-a416-1a42ed26fcf7](https://user-images.githubusercontent.com/47441406/166620404-b51b1eb1-351e-45ef-b123-bfba01337714.png)
.

**Comment by sharlec** [comment]
That is the extra jre in the folder and once remove it, the error message is gone.

 However, the DCNS file is still not working. I tested all other samples in the test.perfeval folder, all other files either work or missing input files(reasonable), but DCNS give me the error message:

Error: Could not find or load main class org.fog.test.perfeval.DCNSFog
Caused by: java.lang.ClassNotFoundException: org.fog.test.perfeval.DCNSFog

This should not  happen as the main function starts in line 52

**Comment by Samodhap** [comment]
Doing a clean build might help solve it.

**Comment by sharlec** [comment]
I just clean build, did not work; I also remove all files and re-downloaded them from Github again, with proper JRE configurations. The error is still there.

**Comment by Samodhap** [comment]
Sorry to hear that. Please try following all the instructions in the Readme. The software has been tested and should work properly. (https://github.com/Cloudslab/iFogSim/blob/main/README.md)

**Comment by sharlec** [comment]
Thanks for the assistance. I did follow the readme instructions, and the ifogsim seems working well just other than the DCSNs file. I guess I may ignore some details in the configuration. I will keep trying. Thank you!

**Comment by Inzark** [comment]
follow steps here - it worked for me 
https://stackoverflow.com/questions/49520858/error-occurred-during-initialization-of-boot-layer-findexception-module-not-fou

**Comment by paghikia** [comment]
i have these problem too but i can't solved them
<img width="1440" alt="Screenshot 2024-01-11 at 5 14 49 PM" src="https://github.com/Cloudslab/iFogSim/assets/67148197/c7dd6fd9-b630-43c5-9e5c-cc0141ddd0f1">

**Comment by mkabeer24** [comment]
Why is this error so prominent, someone should give a comprehensive guide on how to install iFogSim properly all the responses and youtube videos are not addressing this particular error. Thank you

**Comment by mkabeer24** [comment]
> i have these problem too but i can't solved them <img alt="Screenshot 2024-01-11 at 5 14 49 PM" width="1440" src="https://private-user-images.githubusercontent.com/67148197/296013350-c7dd6fd9-b630-43c5-9e5c-cc0141ddd0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzQ3OTQsIm5iZiI6MTcyNDU3NDQ5NCwicGF0aCI6Ii82NzE0ODE5Ny8yOTYwMTMzNTAtYzdkZDZmZDktYjYzMC00M2M1LTllNWMtY2MwMTQxZGRkMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA4MjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZjZhNGE2ODkyYmU0ZTMxNmZlMzJjNTBmNDNmZmI1NzY4NGQ3MmUwNTAxMDA5ZWJiNGMwODhmZmYwYjkwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsybXoClxj1rwWaWp6y4XJnQ8tIUSqGnjXkOBAxfEkQ">

Were you able to fix this?

**Comment by mkabeer24** [comment]
> Why is this error so prominent, someone should give a comprehensive guide on how to install iFogSim properly all the responses and youtube videos are not addressing this particular error. Thank you

I installed the following:
1. JDK 22
2. Eclipse 2024-06
What could be the issue? Thanks

**Comment by mkabeer24** [comment]
> > Why is this error so prominent, someone should give a comprehensive guide on how to install iFogSim properly all the responses and youtube videos are not addressing this particular error. Thank you
> 
> I installed the following:
> 
> 1. JDK 22
> 2. Eclipse 2024-06
>    What could be the issue? Thanks

![ifogsim error](https://github.com/user-attachments/assets/6b6ebf9c-f672-4861-a64f-07a5baa3d198)
![jre library ifogsim](https://github.com/user-attachments/assets/34a2e777-9de6-4a14-8c53-d7ab99c05d6c)

**Comment by mehuli12** [comment]
Hi,

I'm a student working on a project related to edge computing, and I
recently came across your iFogSim tutorials on YouTube. I was really
impressed by your expertise and wanted to reach out to see if you'd be open
to a meeting to help me with some challenges I'm facing with Veins,
OMNET++, and SUMO.

My project is focused on simulating traffic scenarios to demonstrate the
benefits of deploying Fog devices for traffic management, specifically by
reducing network latency to improve outcomes. I'm using the SUMO simulator
to model these scenarios and compare different network latencies, as
iFogSim doesn't support this directly. Before I can use iFogSim, I need to
gather specific computational and network requirements, which I'm planning
to do by implementing a traffic management application with SUMO and
OMNET++, and then profiling the data for use in iFogSim simulations.

Right now, I'm mainly focusing on edge computing, but if time permits, I
hope to use the profiling data from Veins, SUMO, and OMNET++ for iFogSim
simulations later. However, I'm running into some errors with Veins and
could really use your guidance. It would be great if we could set up a
virtual meeting to discuss these issues in more detail. I'm not sure if you
can help with Veins or the other software I'm working with, but any
assistance would be greatly appreciated.

Thanks so much for your time, and I look forward to hearing from you!

Best regards,
Mehuli

**Comment by uselessnormie** [comment]
> > > Why is this error so prominent, someone should give a comprehensive guide on how to install iFogSim properly all the responses and youtube videos are not addressing this particular error. Thank you
> > 
> > 
> > I installed the following:
> > 
> > 1. JDK 22
> > 2. Eclipse 2024-06
> >    What could be the issue? Thanks
> 
> ![ifogsim error](https://private-user-images.githubusercontent.com/43607125/361195958-6b6ebf9c-f672-4861-a64f-07a5baa3d198.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjYxOTIsIm5iZiI6MTcyNjY2NTg5MiwicGF0aCI6Ii80MzYwNzEyNS8zNjExOTU5NTgtNmI2ZWJmOWMtZjY3Mi00ODYxLWE2NGYtMDdhNWJhYTNkMTk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEzMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZTE1NTEzZDhlYTcyMWNiYmE2YzExYWFmNDcxYTBkNTNlZDVkNThlN2VjZGJjNWU4NjIwODMxMDAyMmM2NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3kcEhrYc3qYRZB5EcNCNJjUOvvpwebPM8qrlPcGpUk) ![jre library ifogsim](https://private-user-images.githubusercontent.com/43607125/361195961-34a2e777-9de6-4a14-8c53-d7ab99c05d6c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NjYxOTIsIm5iZiI6MTcyNjY2NTg5MiwicGF0aCI6Ii80MzYwNzEyNS8zNjExOTU5NjEtMzRhMmU3NzctOWRlNi00YTE0LThjNTMtZDdhYjk5YzA1ZDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDEzMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MzczNjIxN2ZkNGUzOWUxMmQzMTgyNTcyYTlhZWZkNjEzZjRmZDk4NTMwNTdjZjNkYjg3ZjNjNGZhNTc2NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SzwbocyJ_vN4umBpUNESpwdyqj8zQjd45jivvLyFKXI)

I was facing same issue 
I deleted module-info.java file ... problem sloved 
![image](https://github.com/user-attachments/assets/90c4ae5a-61bf-45b7-8e72-cff934cf2286)

**Comment by mkabeer24** [comment]
I fixed it too, remove everything, register eclipse PATH, then everything worked.

**Comment by uselessnormie** [comment]
> I fixed it too, remove everything, register eclipse PATH, then everything worked.

ohh another method .. Thank you Hermano

**Comment by noor167886** [comment]
> I fixed it too, remove everything, register eclipse PATH, then everything worked.

im having the same errors in the src and I cant fix it. could you help and tell me how you solved it?

**Comment by RichaSavant** [comment]
> follow steps here - it worked for me https://stackoverflow.com/questions/49520858/error-occurred-during-initialization-of-boot-layer-findexception-module-not-fou

worked!
