### ISSUE TITLE
ClassNotFoundException when running TranslationServiceFog_Clustering

### ISSUE THREAD

**Issue by vijayaramb** [Cloudslab/iFogSim#14]
I am getting the below error while running TranslationServiceFog_Clustering.java,
I have all the jars properly added inclusing math3.

Kindly help me out.

Starting Translation Service...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/math3/util/Pair
	at org.fog.application.Application.addTupleMapping(Application.java:135)
	at org.fog.test.perfeval.TranslationServiceFog_Clustering.createApplication(TranslationServiceFog_Clustering.java:317)
	at org.fog.test.perfeval.TranslationServiceFog_Clustering.main(TranslationServiceFog_Clustering.java:75)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.util.Pair
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more

**Comment by vijayaramb** [comment]
closing it, as i worked when added the jar files in class path instead of module path.

**Comment by vijayaramb** [comment]
closing it
