### ISSUE TITLE
example code not working

### ISSUE THREAD

**Issue by JIBYMARIYAJOSE** [Cloudslab/iFogSim#19]
Starting VRGame...
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 

	at fogsimmaster/org.fog.application.Application.createApplication(Application.java:54)
	at fogsimmaster/org.fog.test.perfeval.VRGameFog.createApplication(VRGameFog.java:241)
	at fogsimmaster/org.fog.test.perfeval.VRGameFog.main(VRGameFog.java:70)
2.Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method createRandomMobilityDatasets(int, String, boolean) from the type CardiovascularHealthMonitoringApplication refers to the missing type ParseException

	at fogsimmaster/org.fog.test.perfeval.CardiovascularHealthMonitoringApplication.main(CardiovascularHealthMonitoringApplication.java:105)
3.Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method createRandomMobilityDatasets(int, String, boolean) from the type CrowdSensing_Microservices_RandomMobility_Clustering refers to the missing type ParseException

	at fogsimmaster/org.fog.test.perfeval.CrowdSensing_Microservices_RandomMobility_Clustering.main(CrowdSensing_Microservices_RandomMobility_Clustering.java:96)
4.Starting Translation Service...
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 

	at fogsimmaster/org.fog.application.Application.createApplication(Application.java:54)
	at fogsimmaster/org.fog.test.perfeval.TranslationServiceFog.createApplication(TranslationServiceFog.java:260)
	at fogsimmaster/org.fog.test.perfeval.TranslationServiceFog.main(TranslationServiceFog.java:67)
Please help with a solution

**Comment by harryjohnlabs** [comment]
does it showing a red x mark in your src floder
