### ISSUE TITLE
iFogsim installation issue

### ISSUE THREAD

**Issue by sultanyousuf** [Cloudslab/iFogSim#29]
Starting DCNS...
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	at TestiFogsimP1/org.fog.application.Application.createApplication(Application.java:54)
	at TestiFogsimP1/org.fog.test.perfeval.DCNSFog.createApplication(DCNSFog.java:229)
	at TestiFogsimP1/org.fog.test.perfeval.DCNSFog.main(DCNSFog.java:68)

**Comment by RichaSavant** [comment]
I have the same issue

**Comment by manashkumarmondal** [comment]
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.fog.mobilitydata.DataParser.parseResourceData(DataParser.java:99)
	at org.fog.placement.LocationHandler.parseResourceInfo(LocationHandler.java:150)
	at org.fog.test.perfeval.CardiovascularHealthMonitoringApplication.createFogDevices(CardiovascularHealthMonitoringApplication.java:162)
	at org.fog.test.perfeval.CardiovascularHealthMonitoringApplication.main(CardiovascularHealthMonitoringApplication.java:109)

**Comment by PavanPavu** [comment]
Starting Cardiovascular Health Monitoring Application...
The dataset: .\dataset\random_usersLocation-melbCBD_1.csv exists already.
The dataset: .\dataset\random_usersLocation-melbCBD_2.csv exists already.
The dataset: .\dataset\random_usersLocation-melbCBD_3.csv exists already.
The dataset: .\dataset\random_usersLocation-melbCBD_4.csv exists already.
The dataset: .\dataset\random_usersLocation-melbCBD_5.csv exists already.
The Mobility dataset used in this simulation for user: 1 is: .\dataset\random_usersLocation-melbCBD_1.csv
The Mobility dataset used in this simulation for user: 2 is: .\dataset\random_usersLocation-melbCBD_2.csv
The Mobility dataset used in this simulation for user: 3 is: .\dataset\random_usersLocation-melbCBD_3.csv
The Mobility dataset used in this simulation for user: 4 is: .\dataset\random_usersLocation-melbCBD_4.csv
The Mobility dataset used in this simulation for user: 5 is: .\dataset\random_usersLocation-melbCBD_5.csv
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.fog.mobilitydata.DataParser.parseResourceData(DataParser.java:99)
	at org.fog.placement.LocationHandler.parseResourceInfo(LocationHandler.java:150)
	at org.fog.test.perfeval.CardiovascularHealthMonitoringApplication.createFogDevices(CardiovascularHealthMonitoringApplication.java:162)
	at org.fog.test.perfeval.CardiovascularHealthMonitoringApplication.main(CardiovascularHealthMonitoringApplication.java:109)
